1. clean the data(outlier,missing values,type conversion)
2. What is the mean value of sepal length
3. sort the sepal width in ascending order.
4. apply all statistical measures on  sepal width and length
5. after cleaning the data ,save the file as 'cleaned_iris.txt' and load to jupyter again to display the values

In [95]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [288]:
import numpy as np


In [289]:
iris = np.genfromtxt(r"C:\Users\pc\Downloads\Iris_clean_-_Copy.csv",dtype = 'float64', delimiter = ',')

In [290]:
iris

array([[      nan,       nan,       nan,       nan],
       [5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000

In [291]:
iris = iris[1:,:]
iris

array([[5.100e+00, 3.500e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.000e+00, 1.400e+00, 2.000e-01],
       [4.700e+00, 3.200e+00, 1.300e+00, 2.000e-01],
       [4.600e+00, 3.100e+00, 1.500e+00, 1.020e+01],
       [5.000e+01, 3.600e+00, 1.400e+00, 2.000e-01],
       [5.400e+00,       nan, 1.700e+00, 4.000e-01],
       [4.600e+00, 3.400e+00, 1.400e+00, 3.000e-01],
       [5.000e+00, 3.400e+00, 1.500e+00, 2.000e-01],
       [4.400e+00, 2.900e+00, 1.400e+00, 2.000e-01],
       [4.900e+00, 3.100e+00,       nan, 1.000e-01],
       [5.400e+00, 3.700e+00, 1.500e+00, 2.000e-01],
       [4.800e+00, 3.400e+00, 1.600e+00, 2.000e-01],
       [4.800e+00, 1.300e+02, 1.400e+00, 1.010e+01],
       [4.300e+00, 3.000e+00, 1.100e+00, 1.000e-01],
       [5.800e+00, 4.000e+00, 1.200e+00, 2.000e-01],
       [5.700e+00, 4.400e+00, 1.500e+00, 4.000e-01],
       [5.040e+01,       nan, 1.300e+00, 4.000e-01],
       [5.100e+00, 3.500e+00, 1.400e+00, 3.000e-01],
       [5.700e+00, 3.800e+00, 1.700e+00, 3.000

In [292]:
sepal_length = iris[1:,0]

In [293]:
sepal_length

array([  4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,   4.9,
         5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,   5.7,
         5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,   5.2,
         5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,   5.5,
         4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,   4.8,
         5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,   6.5,
         5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,   6.1,
         5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,   6.3,
         6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,   5.5,
         5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,   5.5,
         6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,   5.7,
         6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,   6.7,
         7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,   7.7,
         7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,   6.2,
         6.1,   6.4,

In [294]:
Sepal_width = iris[1:,1]
Sepal_width
 

array([  3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,   3.1,
         3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,   3.8,
         3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,   3.5,
         3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,   3.5,
         3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,   3. ,
         3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,   2.8,
         2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,   2.9,
         2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,   2.5,
         nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,   2.4,
         2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,   2.6,
         3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,   2.8,
         3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,   2.5,
         3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,   3.8,
         2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,   2.8,
         3. ,   2.8,

In [295]:
Petal_Length = iris[0:,2]
Petal_Length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [296]:
Petal_Width = iris[0:,3]
Petal_Width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

# SepalLength

In [297]:
sepal_length = iris[1:,0]
sepal_length

array([  4.9,   4.7,   4.6,  50. ,   5.4,   4.6,   5. ,   4.4,   4.9,
         5.4,   4.8,   4.8,   4.3,   5.8,   5.7,  50.4,   5.1,   5.7,
         5.1,   5.4,   5.1,   4.6,   5.1,   4.8,   5. ,   5. ,   5.2,
         5.2,   4.7,   4.8,   5.4,   5.2,   5.5,   4.9,   5. ,   5.5,
         4.9,   4.4,   5.1,   5. ,   4.5,   4.4,   5. ,   5.1,   4.8,
         5.1,   4.6,   5.3,   5. ,   7. ,   6.4,   6.9,   5.5,   6.5,
         5.7, 116.3,   4.9,   6.6,   5.2,   5. ,   5.9,   6. ,   6.1,
         5.6,   6.7,   5.6,   5.8,   6.2,   5.6,   5.9,   6.1,   6.3,
         6.1,   6.4,   6.6,   6.8,   6.7,   6. ,   5.7,   5.5,   5.5,
         5.8,   6. ,   5.4,   6. ,   6.7,   6.3,   5.6,   5.5,   5.5,
         6.1,   5.8,   5. ,   5.6,   5.7,   5.7,   6.2,   5.1,   5.7,
         6.3,   5.8,   7.1,   6.3,   6.5,   7.6,   4.9,   7.3,   6.7,
         7.2,   6.5,   6.4,   6.8,   5.7,   5.8,   6.4,   6.5,   7.7,
         7.7,   6. ,   6.9,   5.6,   7.7,   6.3,   6.7,   7.2,   6.2,
         6.1,   6.4,

In [298]:
np.nanmean(sepal_length)       #mean for sepal_length

7.525625

In [299]:
m = np.nanmedian(sepal_length)      #median
m

5.85

In [300]:
a = np.where(np.isnan(sepal_length),np.nanmedian(sepal_length),sepal_length)  # replace nan with nanmedian
a

array([  4.9 ,   4.7 ,   4.6 ,  50.  ,   5.4 ,   4.6 ,   5.  ,   4.4 ,
         4.9 ,   5.4 ,   4.8 ,   4.8 ,   4.3 ,   5.8 ,   5.7 ,  50.4 ,
         5.1 ,   5.7 ,   5.1 ,   5.4 ,   5.1 ,   4.6 ,   5.1 ,   4.8 ,
         5.  ,   5.  ,   5.2 ,   5.2 ,   4.7 ,   4.8 ,   5.4 ,   5.2 ,
         5.5 ,   4.9 ,   5.  ,   5.5 ,   4.9 ,   4.4 ,   5.1 ,   5.  ,
         4.5 ,   4.4 ,   5.  ,   5.1 ,   4.8 ,   5.1 ,   4.6 ,   5.3 ,
         5.  ,   7.  ,   6.4 ,   6.9 ,   5.5 ,   6.5 ,   5.7 , 116.3 ,
         4.9 ,   6.6 ,   5.2 ,   5.  ,   5.9 ,   6.  ,   6.1 ,   5.6 ,
         6.7 ,   5.6 ,   5.8 ,   6.2 ,   5.6 ,   5.9 ,   6.1 ,   6.3 ,
         6.1 ,   6.4 ,   6.6 ,   6.8 ,   6.7 ,   6.  ,   5.7 ,   5.5 ,
         5.5 ,   5.8 ,   6.  ,   5.4 ,   6.  ,   6.7 ,   6.3 ,   5.6 ,
         5.5 ,   5.5 ,   6.1 ,   5.8 ,   5.  ,   5.6 ,   5.7 ,   5.7 ,
         6.2 ,   5.1 ,   5.7 ,   6.3 ,   5.8 ,   7.1 ,   6.3 ,   6.5 ,
         7.6 ,   4.9 ,   7.3 ,   6.7 ,   7.2 ,   6.5 ,   6.4 ,   6.8 ,
      

In [301]:
ou = a > 8          # outlier

In [302]:
sepal_length = np.where(ou,5,a)
sepal_length

array([4.9 , 4.7 , 4.6 , 5.  , 5.4 , 4.6 , 5.  , 4.4 , 4.9 , 5.4 , 4.8 ,
       4.8 , 4.3 , 5.8 , 5.7 , 5.  , 5.1 , 5.7 , 5.1 , 5.4 , 5.1 , 4.6 ,
       5.1 , 4.8 , 5.  , 5.  , 5.2 , 5.2 , 4.7 , 4.8 , 5.4 , 5.2 , 5.5 ,
       4.9 , 5.  , 5.5 , 4.9 , 4.4 , 5.1 , 5.  , 4.5 , 4.4 , 5.  , 5.1 ,
       4.8 , 5.1 , 4.6 , 5.3 , 5.  , 7.  , 6.4 , 6.9 , 5.5 , 6.5 , 5.7 ,
       5.  , 4.9 , 6.6 , 5.2 , 5.  , 5.9 , 6.  , 6.1 , 5.6 , 6.7 , 5.6 ,
       5.8 , 6.2 , 5.6 , 5.9 , 6.1 , 6.3 , 6.1 , 6.4 , 6.6 , 6.8 , 6.7 ,
       6.  , 5.7 , 5.5 , 5.5 , 5.8 , 6.  , 5.4 , 6.  , 6.7 , 6.3 , 5.6 ,
       5.5 , 5.5 , 6.1 , 5.8 , 5.  , 5.6 , 5.7 , 5.7 , 6.2 , 5.1 , 5.7 ,
       6.3 , 5.8 , 7.1 , 6.3 , 6.5 , 7.6 , 4.9 , 7.3 , 6.7 , 7.2 , 6.5 ,
       6.4 , 6.8 , 5.7 , 5.8 , 6.4 , 6.5 , 7.7 , 7.7 , 6.  , 6.9 , 5.6 ,
       7.7 , 6.3 , 6.7 , 7.2 , 6.2 , 6.1 , 6.4 , 5.  , 5.85, 5.85, 6.4 ,
       6.3 , 6.1 , 7.7 , 6.3 , 6.4 , 6.  , 6.9 , 6.7 , 6.9 , 5.8 , 6.8 ,
       6.7 , 6.7 , 6.3 , 6.5 , 6.2 , 5.9 , 5.6 , 7.

In [303]:
sepal_length = np.array(sepal_length,dtype = "float16")
sepal_length

array([4.9 , 4.7 , 4.6 , 5.  , 5.4 , 4.6 , 5.  , 4.4 , 4.9 , 5.4 , 4.8 ,
       4.8 , 4.3 , 5.8 , 5.7 , 5.  , 5.1 , 5.7 , 5.1 , 5.4 , 5.1 , 4.6 ,
       5.1 , 4.8 , 5.  , 5.  , 5.2 , 5.2 , 4.7 , 4.8 , 5.4 , 5.2 , 5.5 ,
       4.9 , 5.  , 5.5 , 4.9 , 4.4 , 5.1 , 5.  , 4.5 , 4.4 , 5.  , 5.1 ,
       4.8 , 5.1 , 4.6 , 5.3 , 5.  , 7.  , 6.4 , 6.9 , 5.5 , 6.5 , 5.7 ,
       5.  , 4.9 , 6.6 , 5.2 , 5.  , 5.9 , 6.  , 6.1 , 5.6 , 6.7 , 5.6 ,
       5.8 , 6.2 , 5.6 , 5.9 , 6.1 , 6.3 , 6.1 , 6.4 , 6.6 , 6.8 , 6.7 ,
       6.  , 5.7 , 5.5 , 5.5 , 5.8 , 6.  , 5.4 , 6.  , 6.7 , 6.3 , 5.6 ,
       5.5 , 5.5 , 6.1 , 5.8 , 5.  , 5.6 , 5.7 , 5.7 , 6.2 , 5.1 , 5.7 ,
       6.3 , 5.8 , 7.1 , 6.3 , 6.5 , 7.6 , 4.9 , 7.3 , 6.7 , 7.2 , 6.5 ,
       6.4 , 6.8 , 5.7 , 5.8 , 6.4 , 6.5 , 7.7 , 7.7 , 6.  , 6.9 , 5.6 ,
       7.7 , 6.3 , 6.7 , 7.2 , 6.2 , 6.1 , 6.4 , 5.  , 5.85, 5.85, 6.4 ,
       6.3 , 6.1 , 7.7 , 6.3 , 6.4 , 6.  , 6.9 , 6.7 , 6.9 , 5.8 , 6.8 ,
       6.7 , 6.7 , 6.3 , 6.5 , 6.2 , 5.9 , 5.6 , 7.

# sepal width

In [304]:
sepal_width = iris[0:,1]
sepal_width
 

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [305]:
np.nanmean(sepal_width) 

4.713207547169812

In [306]:
np.nanmedian(sepal_width) 

3.0

In [307]:
Iris = np.where(sepal_width == -1,np.nan,sepal_width)       #nan values
Iris

array([  3.5,   3. ,   3.2,   3.1,   3.6,   nan,   3.4,   3.4,   2.9,
         3.1,   3.7,   3.4, 130. ,   3. ,   4. ,   4.4,   nan,   3.5,
         3.8,   3.8,   3.4,   3.7,   3.6,   3.3,   3.4,   3. ,  34. ,
         3.5,   3.4,   3.2,   3.1,   3.4,   4.1,   4.2,   3.1,   3.2,
         3.5,   3.1,   3. ,   3.4,   3.5,   2.3,   3.2,   3.5,   3.8,
         3. ,   3.8,   3.2,   3.7,   3.3,   3.2,   3.2,   nan,   2.3,
         2.8,   2.8,   3.3,   2.4,   2.9,   2.7,   2. ,   3. ,   2.2,
         2.9,   2.9,   3.1,   3. ,   2.7,   2.2,   2.5,   3.2,   2.8,
         2.5,   nan,   2.9,   3. ,   2.8,   3. ,   2.9,   2.6,   2.4,
         2.4,   2.7,   2.7,   3. ,   3.4,   3.1,   2.3,   3. ,   2.5,
         2.6,   3. , 112.6,   2.3,   2.7,   3. ,   2.9,   2.9,   2.5,
         2.8,   3.3,   2.7,   3. ,   2.9,   3. ,   3. ,   2.5,   2.9,
         2.5,   3.6,   3.2,   2.7,   3. ,   2.5,   2.8,   3.2,   3. ,
         3.8,   2.6,   2.2,   3.2,   2.8,   2.8,   2.7,   3.3,   3.2,
         2.8,   3. ,

In [308]:
ou = (Iris > 5) | (Iris < 2)         # outlier

In [309]:
sepal_width = np.where(ou,3,Iris)
sepal_width

array([3.5, 3. , 3.2, 3.1, 3.6, nan, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, nan, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7])

In [310]:
sepal_width = np.array(sepal_width,dtype = "float16")
sepal_width

array([3.5, 3. , 3.2, 3.1, 3.6, nan, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, nan, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3. , 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       nan, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, nan, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 3. , 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, nan, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, nan, 2.5, 3. , 3.4, 3. , 2.8, 2.8, 2.7, 3.3, 3.2, 2.5,
       2.9, 2.5, 3. , 2.8, 2.8, 2.7, 3.6, 3.2, 2.7], dtype=float16)

# patel length

In [311]:
Petal_Length = iris[0:,2]
Petal_Length

array([ 1.4,  1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,
        1.6,  1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,
        1. ,  1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,
        1.4,  1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,
        1.9,  1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,
        4.5,  4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,
        4.5,  4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,
        5. ,  4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,
        4.1,  4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,
        4.1,  6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,
        5.1,  5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,
        4.9,  6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,
        5.6,  5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,
        5.9,  5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4

In [312]:
Petal_Length = iris[1:,2]
Petal_Length

array([ 1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  nan,  1.5,  1.6,
        1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,  1. ,
        1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,  1.4,
        1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,  1.9,
        1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,  4.5,
        4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,  4.5,
        4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,  5. ,
        4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,  4.1,
        4. ,  4.4,  nan,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,  4.1,
        6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,  5.1,
        5.3,  nan,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,  4.9,
        6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  nan,  5.6,
        5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  nan,  5.1,  5.1,  5.9,
        5.7,  nan,  5. ,  5.2,  5.4,  5.1,  4.9,  6

In [313]:
np.nanmedian(Petal_Length)

4.5

In [314]:
a = np.where(np.isnan(Petal_Length),np.nanmedian(Petal_Length),Petal_Length)     # replace missing value with nanmedian
a

array([ 1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,  1.5,  1.6,
        1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,  1. ,
        1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,  1.4,
        1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3, 13. ,  1.3,  1.6,  1.9,
        1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,  4.5,
        4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,  4.5,
        4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,  5. ,
        4.5,  3.5, 13.8,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,  4.1,
        4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,  4.1,
        6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,  5.1,
        5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,  4.9,
        6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  4.5,  5.6,
        5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,  5.1,  5.9,
        5.7,  4.5,  5. ,  5.2,  5.4,  5.1,  4.9,  6

In [315]:
ou = (a < 1) | (a > 7)               # outlier

In [316]:
Petal_Length = np.where(ou,4,a)
Petal_Length

array([1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4, 1.1,
       1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6,
       1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5,
       1.3, 4. , 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9,
       4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6, 4.4,
       4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. , 4.5,
       3.5, 4. , 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4, 4.5,
       4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6, 5.8,
       6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5, 6.7,
       6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8, 6.1,
       4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1, 5.9,
       5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5, 6.3,
       5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3])

In [317]:
Petal_Length = np.array(Petal_Length,dtype = "float16")
Petal_Length

array([1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 4.5, 1.5, 1.6, 1.4, 1.1,
       1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6, 1.6,
       1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3, 1.5,
       1.3, 4. , 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5, 4.9,
       4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6, 4.4,
       4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. , 4.5,
       3.5, 4. , 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4, 4.5,
       4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6, 5.8,
       6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 4.5, 5. , 5.1, 5.3, 5.5, 6.7,
       6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8, 6.1,
       4.5, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 4.5, 5.1, 5.1, 5.9,
       5.7, 4.5, 5. , 5.2, 5.4, 5.1, 4.9, 6.7, 4.9, 5.7, 6. , 4.5, 6.3,
       5.8, 5.1, 4.9, 6.7, 4.9, 6.1, 5.1, 5.3], dtype=float16)

# patel width

In [318]:
Petal_Width = iris[0:,3]
Petal_Width

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [319]:
np.nanmedian(Petal_Width)

1.5

In [320]:
a = np.where(np.isnan(Petal_Width),np.nanmedian(Petal_Width),Petal_Width)   # replace missing value with nanmedian
a

array([2.000e-01, 2.000e-01, 2.000e-01, 1.020e+01, 2.000e-01, 4.000e-01,
       3.000e-01, 2.000e-01, 2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01,
       1.010e+01, 1.000e-01, 2.000e-01, 4.000e-01, 4.000e-01, 3.000e-01,
       3.000e-01, 3.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 5.000e-01,
       2.000e-01, 2.000e-01, 4.000e-01, 2.000e-01, 1.102e+02, 2.000e-01,
       2.000e-01, 4.000e-01, 1.000e-01, 2.000e-01, 1.000e-01, 2.000e-01,
       2.000e-01, 1.000e-01, 2.000e-01, 2.000e-01, 3.000e-01, 3.000e-01,
       2.000e-01, 6.000e-01, 4.000e-01, 3.000e-01, 2.000e-01, 2.000e-01,
       2.000e-01, 2.000e-01, 1.400e+00, 1.500e+00, 1.500e+00, 1.300e+00,
       1.500e+00, 1.300e+00, 1.600e+00, 1.600e+01, 1.300e+00, 1.400e+00,
       1.000e+00, 1.500e+00, 1.000e+00, 1.400e+00, 1.300e+00, 1.400e+00,
       1.500e+00, 1.000e+00, 1.500e+00, 1.100e+00, 1.800e+00, 1.300e+00,
       1.500e+00, 1.200e+00, 1.300e+00, 1.400e+00, 1.400e+00, 1.700e+00,
       1.500e+00, 1.000e+00, 1.100e+00, 1.000e+00, 

In [321]:
ou = a > 11  # outlier

In [322]:
Petal_Width = np.where(ou,2,a)
Petal_Width

array([ 0.2,  0.2,  0.2, 10.2,  0.2,  0.4,  0.3,  0.2,  0.2,  0.1,  0.2,
        0.2, 10.1,  0.1,  0.2,  0.4,  0.4,  0.3,  0.3,  0.3,  0.2,  0.4,
        0.2,  0.5,  0.2,  0.2,  0.4,  0.2,  2. ,  0.2,  0.2,  0.4,  0.1,
        0.2,  0.1,  0.2,  0.2,  0.1,  0.2,  0.2,  0.3,  0.3,  0.2,  0.6,
        0.4,  0.3,  0.2,  0.2,  0.2,  0.2,  1.4,  1.5,  1.5,  1.3,  1.5,
        1.3,  1.6,  2. ,  1.3,  1.4,  1. ,  1.5,  1. ,  1.4,  1.3,  1.4,
        1.5,  1. ,  1.5,  1.1,  1.8,  1.3,  1.5,  1.2,  1.3,  1.4,  1.4,
        1.7,  1.5,  1. ,  1.1,  1. ,  1.2,  1.6,  1.5,  1.6,  1.5,  1.3,
        1.3,  1.3,  1.2,  1.4,  1.2,  1. ,  1.3,  1.2,  1.3,  1.3,  2. ,
        1.3,  2.5,  1.9,  2.1,  1.8,  2.2,  2.1,  1.7,  1.8,  1.8,  2.5,
        2. ,  1.9,  2.1,  2. ,  2.4,  2.3,  1.8,  2.2,  2.3,  1.5,  2.3,
        2. ,  2. ,  1.8,  2.1,  1.8,  1.8,  1.8,  2.1,  1.6,  1.9,  2. ,
        2.2,  1.5,  1.4,  2.3,  2.4,  1.8,  1.8,  2.1,  2.4,  2.3,  1.9,
        2.3,  2.5,  2.3,  1.9,  2. ,  2.3,  1.8,  2

In [323]:
Petal_Width = np.array(Petal_Width,dtype = "float16")
Petal_Width

array([ 0.2,  0.2,  0.2, 10.2,  0.2,  0.4,  0.3,  0.2,  0.2,  0.1,  0.2,
        0.2, 10.1,  0.1,  0.2,  0.4,  0.4,  0.3,  0.3,  0.3,  0.2,  0.4,
        0.2,  0.5,  0.2,  0.2,  0.4,  0.2,  2. ,  0.2,  0.2,  0.4,  0.1,
        0.2,  0.1,  0.2,  0.2,  0.1,  0.2,  0.2,  0.3,  0.3,  0.2,  0.6,
        0.4,  0.3,  0.2,  0.2,  0.2,  0.2,  1.4,  1.5,  1.5,  1.3,  1.5,
        1.3,  1.6,  2. ,  1.3,  1.4,  1. ,  1.5,  1. ,  1.4,  1.3,  1.4,
        1.5,  1. ,  1.5,  1.1,  1.8,  1.3,  1.5,  1.2,  1.3,  1.4,  1.4,
        1.7,  1.5,  1. ,  1.1,  1. ,  1.2,  1.6,  1.5,  1.6,  1.5,  1.3,
        1.3,  1.3,  1.2,  1.4,  1.2,  1. ,  1.3,  1.2,  1.3,  1.3,  2. ,
        1.3,  2.5,  1.9,  2.1,  1.8,  2.2,  2.1,  1.7,  1.8,  1.8,  2.5,
        2. ,  1.9,  2.1,  2. ,  2.4,  2.3,  1.8,  2.2,  2.3,  1.5,  2.3,
        2. ,  2. ,  1.8,  2.1,  1.8,  1.8,  1.8,  2.1,  1.6,  1.9,  2. ,
        2.2,  1.5,  1.4,  2.3,  2.4,  1.8,  1.8,  2.1,  2.4,  2.3,  1.9,
        2.3,  2.5,  2.3,  1.9,  2. ,  2.3,  1.8,  2

# 2.what is the mean value of sepal length

In [324]:
sepal_length= np.mean(sepal_length)  # mean
sepal_length

5.855

# 3.sort the sepal width in ascending order

In [325]:
sepal_width  = np.sort(sepal_width)    #sort
sepal_width

array([2. , 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5,
       2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.7,
       2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.8, 2.8,
       2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8,
       2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. , 3. ,
       3. , 3. , 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.2,
       3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2,
       3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.4,
       3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5, 3.6,
       3.6, 3.6, 3.6, 3.7, 3.7, 3.7, 3.8, 3.8, 3.8, 3.8, 3.8, 3.8, 4. ,
       4.1, 4.2, 4.4, nan, nan, nan, nan, nan, nan], dtype=float16)

# 4.apply all statistical measures on sepal with and length

sepal width

mean

In [326]:
np.nanmean(sepal_width)

3.03

median

In [327]:
np.nanmedian(sepal_width)   

3.0

Range

In [328]:
Range = np.nanmax(sepal_width)-np.nanmin(sepal_width)  
Range

2.398

IQR

In [329]:
Q3 = np.nanpercentile(sepal_width,75)  
Q1 = np.nanpercentile(sepal_width,25)
IQR = Q3 - Q1
IQR

0.5

standard deviation

In [330]:
np.nanstd(sepal_width) 

0.418

# sepal length

mean

In [331]:
np.nanmean(sepal_length)  

5.855

median

In [332]:
np.nanmedian(sepal_length) 

5.855

variance

In [333]:
np.nanvar(sepal_length)

0.0

IQR

In [334]:
Q3 = np.nanpercentile(sepal_length,75)  
Q1 = np.nanpercentile(sepal_length,25)
IQR = Q3 - Q1
IQR

0.0

Range

In [335]:
Range  = np.nanmax(sepal_length) - np.nanmin(sepal_length) 
Range


0.0

standard deviation

In [336]:
np.nanstd(sepal_length)

0.0

# 5.after cleaning the data save the file as "cleaned_Iris.txt" and load to jupter again

In [337]:
sepal = np.hstack((sepal_length,sepal_width))
sepal

array([5.855, 2.   , 2.2  , 2.2  , 2.2  , 2.3  , 2.3  , 2.3  , 2.3  ,
       2.4  , 2.4  , 2.4  , 2.5  , 2.5  , 2.5  , 2.5  , 2.5  , 2.5  ,
       2.5  , 2.5  , 2.5  , 2.5  , 2.6  , 2.6  , 2.6  , 2.6  , 2.7  ,
       2.7  , 2.7  , 2.7  , 2.7  , 2.7  , 2.7  , 2.7  , 2.7  , 2.7  ,
       2.7  , 2.7  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  ,
       2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  , 2.8  ,
       2.8  , 2.9  , 2.9  , 2.9  , 2.9  , 2.9  , 2.9  , 2.9  , 2.9  ,
       2.9  , 2.9  , 2.9  , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   ,
       3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   ,
       3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   , 3.   ,
       3.   , 3.   , 3.   , 3.   , 3.1  , 3.1  , 3.1  , 3.1  , 3.1  ,
       3.1  , 3.1  , 3.1  , 3.1  , 3.1  , 3.2  , 3.2  , 3.2  , 3.2  ,
       3.2  , 3.2  , 3.2  , 3.2  , 3.2  , 3.2  , 3.2  , 3.2  , 3.2  ,
       3.2  , 3.2  , 3.3  , 3.3  , 3.3  , 3.3  , 3.3  , 3.3  , 3.3  ,
       3.4  , 3.4  ,

In [338]:
Petal= np.hstack((Petal_Length,Petal_Width))
Petal

array([ 1.4,  1.3,  1.5,  1.4,  1.7,  1.4,  1.5,  1.4,  4.5,  1.5,  1.6,
        1.4,  1.1,  1.2,  1.5,  1.3,  1.4,  1.7,  1.5,  1.7,  1.5,  1. ,
        1.7,  1.9,  1.6,  1.6,  1.5,  1.4,  1.6,  1.6,  1.5,  1.5,  1.4,
        1.5,  1.2,  1.3,  1.5,  1.3,  1.5,  1.3,  4. ,  1.3,  1.6,  1.9,
        1.4,  1.6,  1.4,  1.5,  1.4,  4.7,  4.5,  4.9,  4. ,  4.6,  4.5,
        4.7,  3.3,  4.6,  3.9,  3.5,  4.2,  4. ,  4.7,  3.6,  4.4,  4.5,
        4.1,  4.5,  3.9,  4.8,  4. ,  4.9,  4.7,  4.3,  4.4,  4.8,  5. ,
        4.5,  3.5,  4. ,  3.7,  3.9,  5.1,  4.5,  4.5,  4.7,  4.4,  4.1,
        4. ,  4.4,  4.5,  4. ,  3.3,  4.2,  4.2,  4.2,  4.3,  3. ,  4.1,
        6. ,  5.1,  5.9,  5.6,  5.8,  6.6,  4.5,  6.3,  5.8,  6.1,  5.1,
        5.3,  4.5,  5. ,  5.1,  5.3,  5.5,  6.7,  6.9,  5. ,  5.7,  4.9,
        6.7,  4.9,  5.7,  6. ,  4.8,  4.9,  5.6,  5.8,  6.1,  4.5,  5.6,
        5.1,  5.6,  6.1,  5.6,  5.5,  4.8,  5.4,  4.5,  5.1,  5.1,  5.9,
        5.7,  4.5,  5. ,  5.2,  5.4,  5.1,  4.9,  6

In [339]:
iris = np.hstack((sepal,Petal))
iris

array([ 5.855,  2.   ,  2.2  ,  2.2  ,  2.2  ,  2.3  ,  2.3  ,  2.3  ,
        2.3  ,  2.4  ,  2.4  ,  2.4  ,  2.5  ,  2.5  ,  2.5  ,  2.5  ,
        2.5  ,  2.5  ,  2.5  ,  2.5  ,  2.5  ,  2.5  ,  2.6  ,  2.6  ,
        2.6  ,  2.6  ,  2.7  ,  2.7  ,  2.7  ,  2.7  ,  2.7  ,  2.7  ,
        2.7  ,  2.7  ,  2.7  ,  2.7  ,  2.7  ,  2.7  ,  2.8  ,  2.8  ,
        2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,
        2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.8  ,  2.9  ,
        2.9  ,  2.9  ,  2.9  ,  2.9  ,  2.9  ,  2.9  ,  2.9  ,  2.9  ,
        2.9  ,  2.9  ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,
        3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.   ,  3.1  ,  3.1  ,
        3.1  ,  3.1  ,  3.1  ,  3.1  ,  3.1  ,  3.1  ,  3.1  ,  3.1  ,
        3.2  ,  3.2  ,  3.2  ,  3.2  ,  3.2  ,  3.2  ,  3.2  ,  3.2  ,
      

In [340]:
np.savetxt('cleaned_iris.txt',iris)

In [341]:
np.loadtxt('cleaned_iris.txt')

array([ 5.85546875,  2.        ,  2.19921875,  2.19921875,  2.19921875,
        2.30078125,  2.30078125,  2.30078125,  2.30078125,  2.40039062,
        2.40039062,  2.40039062,  2.5       ,  2.5       ,  2.5       ,
        2.5       ,  2.5       ,  2.5       ,  2.5       ,  2.5       ,
        2.5       ,  2.5       ,  2.59960938,  2.59960938,  2.59960938,
        2.59960938,  2.69921875,  2.69921875,  2.69921875,  2.69921875,
        2.69921875,  2.69921875,  2.69921875,  2.69921875,  2.69921875,
        2.69921875,  2.69921875,  2.69921875,  2.80078125,  2.80078125,
        2.80078125,  2.80078125,  2.80078125,  2.80078125,  2.80078125,
        2.80078125,  2.80078125,  2.80078125,  2.80078125,  2.80078125,
        2.80078125,  2.80078125,  2.80078125,  2.80078125,  2.80078125,
        2.90039062,  2.90039062,  2.90039062,  2.90039062,  2.90039062,
        2.90039062,  2.90039062,  2.90039062,  2.90039062,  2.90039062,
        2.90039062,  3.        ,  3.        ,  3.        ,  3.  