In [4]:
import numpy as np

# creating an array

In [5]:
arr = np.array([10,12,15,24,59,78,64,12,8,91,10])
arr

array([10, 12, 15, 24, 59, 78, 64, 12,  8, 91, 10])

In [6]:
arr1 = [1,2,12,15,17,22]

In [7]:
n = np.array(arr1)
n

array([ 1,  2, 12, 15, 17, 22])

In [8]:
tup = (66,12,6,8,9,23,30)          
arr2 = np.array(tup)
arr2

array([66, 12,  6,  8,  9, 23, 30])

In [9]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(23)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])

In [11]:
np.arange(1,23)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [12]:
np.linspace(0,40,10)

array([ 0.        ,  4.44444444,  8.88888889, 13.33333333, 17.77777778,
       22.22222222, 26.66666667, 31.11111111, 35.55555556, 40.        ])

# 2. Create a 1D NumPy array containing the first 12 positive integer as arr1

In [13]:
arr1 = np.array(range(1,13))
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Create an array containing 20 elements from 0 to 12 using linspace

In [98]:
array2 = np.linspace(0,12,20)
array2

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

# Find all the attributes of array1 and array2

# array 1

In [15]:
arr1.dtype

dtype('int32')

In [16]:
arr1.nbytes

48

In [17]:
arr1.ndim

1

In [18]:
arr1.min()

1

In [19]:
arr1.max()

12

In [28]:
arr1.itemsize

4

In [33]:
arr1.size

12

# array 2

In [20]:
array2.dtype

dtype('float64')

In [21]:
array2.nbytes

160

In [22]:
array2.ndim

1

In [23]:
array2.max()

12.0

In [24]:
array2.min()

0.0

In [31]:
array2.itemsize

8

In [32]:
array2.size

20

# Apply measure and describe the data (attributes and descriptive statistics) to above arrays

In [34]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# measure of tendency of arr1

In [37]:
np.mean(arr1)

6.5

In [39]:
np.median(arr1)

6.5

# measure of spread of arr1

In [44]:
#range
np.max(arr1)

12

In [45]:
np.min(arr1)


1

In [46]:
range = np.max(arr1) - np.min(arr1)
range

11

In [47]:
# variance
np.var(arr1)

11.916666666666666

In [48]:
# standard deviation
np.std(arr1)

3.452052529534663

# IQR for arr1

In [49]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [50]:
q1 = np.percentile(arr1,25)
q1

3.75

In [52]:
q2 = np.percentile(arr1,50)
q2

6.5

In [53]:
q3 = np.percentile(arr1,75)
q3

9.25

In [54]:
IQR = q3 - q1
IQR

5.5

In [55]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-4.5

In [56]:
upper_limit = q3 + (1.5 * IQR)
upper_limit


17.5

# measure of central tendency of array2


In [57]:
np.mean(array2)

5.999999999999999

In [58]:
np.median(array2)

6.0

# measure of spread for array2

In [59]:
# range
np.max(array2)


12.0

In [60]:
np.min(array2)

0.0

In [61]:
range = np.max(array2) - np.min(array2)
range

12.0

In [62]:
### variance
np.var(array2)

13.26315789473684

In [63]:
### standard deviation
np.std(array2)

3.6418618720013036

# IQR for array2

In [66]:
q1 = np.percentile(array2,25)
q1

3.0

In [67]:
q2 = np.percentile(array2,50)
q2

6.0

In [71]:
q3= np.percentile(array2,75)
q3

9.0

In [74]:
IQR = q3 - q1
IQR

6.0

In [75]:
lower_limit = q1 - (1.5 * IQR)
lower_limit

-6.0

In [76]:
upper_limit = q3 + (1.5 * IQR)
upper_limit

18.0