Data Cleaning using numpy
The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

1 Find the no of outliers and missing values?
2 replace the outliers with 45 and missing value with 87.
3 what is the average marks of students after 2nd step?
4 How many students got less than 60 marks?
5 what is the maximum marks?
6 Convert the marks to float32.



 Solving Linear Equations
 
1. 2x + 3y - z = 10

   x - y + 2z = 5

   3x + 2y + z = 12

2. 2x + y - z + 3w = 8

   3x - 2y + 2z + 2w = 1

   x + 3y - 2z + w = 7

   4x - y + z - 2w = 3

3. 4x + 2y - 3z = 10

  -2x + 3y + z = -3

   x - y + 2z = 4


Solve the system of equations using NumPy's linalg.solve function.

Conditional Selection with np.where()
1 Generate a random 1D array A of 10 integers between 1 and 100.

2 Use np.where() to find the indices where the elements of A are greater than 50.

3 Create a new array B that contains elements from A where the condition is met.

4 Calculate the mean of array B and print it along with arrays A and B.

Replace Values with np.where()
1 Create a 4x4 random integer matrix C with values between -10 and 10.

2 Use np.where() to replace all negative values in matrix C with 0.

3 Print the original matrix C and the modified matrix.

 

In [96]:
import numpy as np

In [97]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44])

# 1 Find the no of outliers and missing values?

In [36]:
outliers = (marks[(marks > 100) | (marks < 0)])
outliers

array([188., 120., 122.])

In [37]:
marks[marks>100]

array([188., 120., 122.])

In [38]:
len(marks[marks>100])

3

In [39]:
np.isnan(marks)


array([False, False,  True, False, False, False, False, False, False,
       False, False, False,  True,  True, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False])

In [40]:
sum(np.isnan(marks))   # Missing vales 

4

# 2 replace the outliers with 45 and missing value with 87.

In [41]:
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [42]:
marks = np.where(np.isnan(marks),87,marks).astype('float32')#missing values replaced with 87
marks

array([ 44.,  24.,  87.,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  87.,  87.,   3.,  56.,  81.,  59., 122.,  92.,  87.,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.], dtype=float32)

In [48]:
cond = (marks > 100) | (marks < 0)
cond

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [49]:
np.sum(cond)

3

In [52]:
marks = np.where(cond,45,marks)

In [53]:
marks

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

# 3 what is the average marks of students after 2nd step?

In [54]:
average = np.mean(marks)
average

56.96552

# 4 How many students got less than 60 marks?

In [56]:
len(marks[marks<60])

18

# 5 what is the maximum marks?

In [62]:
np.max(marks)

97.0

# 6 Convert the marks to float32.


In [68]:
np.array(marks,dtype = "float64")

array([44., 24., 87., 59., 32., 96., 45., 52., 62., 58., 52., 45., 87.,
       87.,  3., 56., 81., 59., 45., 92., 87., 87., 96., 97.,  1., 19.,
        2., 53., 44.])

In [69]:
marks.dtype

dtype('float32')

# Solving Linear Equations

2x + 3y - z = 10

x - y + 2z = 5

3x + 2y + z = 12

In [70]:
x = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
x

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [71]:
y = np.array([10,5,12])
y

array([10,  5, 12])

In [72]:
np.linalg.solve(x,y)

array([-7.36952666e+15,  7.36952666e+15,  7.36952666e+15])

2x + y - z + 3w = 8

3x - 2y + 2z + 2w = 1

x + 3y - 2z + w = 7

4x - y + z - 2w = 3

In [74]:
s = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
s

array([[ 2,  1, -1,  3],
       [ 3, -2,  2,  2],
       [ 1,  3, -2,  1],
       [ 4, -1,  1, -2]])

In [75]:
a = np.array([8,1,7,3])
a

array([8, 1, 7, 3])

In [76]:
np.linalg.solve(s,a)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

4x + 2y - 3z = 10

-2x + 3y + z = -3

x - y + 2z = 4

In [77]:
v = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
v

array([[ 4,  2, -3],
       [-2,  3,  1],
       [ 1, -1,  2]])

In [78]:
t = np.array([10,-3,4])
t

array([10, -3,  4])

In [79]:
np.linalg.solve(v,t)

array([2.85365854, 0.6097561 , 0.87804878])

# Conditional Selection with np.where()

1.Generate a random 1D array A of 10 integers between 1 and 100.

In [84]:
arr1 = np.random.randint(1,100,10)
A = np.array(arr1)
A

array([58, 66, 68, 64, 11, 99, 13, 28, 12, 73])

2 Use np.where() to find the indices where the elements of A are greater than 50.

In [86]:
elmt = A>50
print(A[elmt])
np.where(elmt)

[58 66 68 64 99 73]


(array([0, 1, 2, 3, 5, 9], dtype=int64),)

3.Create a new array B that contains elements from A where the condition is met.


In [87]:
B = np.array(A[A>50])
B

array([58, 66, 68, 64, 99, 73])

4.Calculate the mean of array B and print it along with arrays A and B.

In [98]:
np.mean(A)

49.2

In [99]:
np.mean(B)

71.33333333333333

# Replace Values with np.where()

1.Create a 4x4 random integer matrix C with values between -10 and 10

In [106]:
c = np.random.randint(-10,10,16).reshape(4,4)
c

array([[  9,  -6,  -1,  -1],
       [-10,  -5,   8,  -6],
       [ -1, -10,   7,  -2],
       [ -7,   4,   2,  -9]])

2.Use np.where() to replace all negative values in matrix C with 0

In [113]:
modified = np.where(c<0,0,c)
modified

array([[9, 0, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 7, 0],
       [0, 4, 2, 0]])

3.Print the original matrix C and the modified matrix.

In [114]:
c


array([[  9,  -6,  -1,  -1],
       [-10,  -5,   8,  -6],
       [ -1, -10,   7,  -2],
       [ -7,   4,   2,  -9]])

In [115]:
modified

array([[9, 0, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 7, 0],
       [0, 4, 2, 0]])