# pandas Series


1 Create pandas series with different data types in different ways

2 Find the attributes of Series of [10,30,40,1,3,6,14,18,23] with index starts from 100

3 create salaries of 30 employee salaries randomly from 30000-90000 then measure and describe the data using pandas series.

4 What are the similaraties and differences between pandas series and nnumpy array.Prove it with code.

5 create pandas series with ranges from 100 to 150 then apply indexing and slicing on it.

In [1]:
import pandas as pd
import numpy as np

# 1 Create pandas series with different data types in different ways

# from list

In [2]:
n = [1,2,3,4,5,6,7,8]
pd.Series(n)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [3]:
List = [1,2,3,4,5,6,7,8]
List1 = pd.Series(List)
List1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [4]:
#method 2
list = ['A', 'i', 's', 'h', 'u']
  
# create series form a list
ser = pd.Series(list)
print(ser)

0    A
1    i
2    s
3    h
4    u
dtype: object


# from dictionary

In [5]:
elements_names = {1: "Helium", 2:"sodium", 3:"Hydrogen", 4:"carbon", 5:"iron", 6: "potassium", 7: "copper", 8:"oxygen"}

In [6]:
pd.Series(elements_names)

1       Helium
2       sodium
3     Hydrogen
4       carbon
5         iron
6    potassium
7       copper
8       oxygen
dtype: object

In [7]:
#method 2
dict = {'rice': 500,
        'fruits': 100,
        'vegetables': 300}
 
# create series from dictionary
ser = pd.Series(dict)
 
print(ser)

rice          500
fruits        100
vegetables    300
dtype: int64


# from tuple

In [8]:
movie_names = ("Raju","vijay","Prabhas","Mahesh","Sai")
pd.Series(movie_names)

0       Raju
1      vijay
2    Prabhas
3     Mahesh
4        Sai
dtype: object

# from array

In [9]:
# simple array
data = np.array(['g', 'e', 'e', 'k', 's'])
 
ser = pd.Series(data)
print(ser)


0    g
1    e
2    e
3    k
4    s
dtype: object


In [10]:
# providing an index
ser = pd.Series(data, index=[10, 11, 12, 13, 14])
print(ser)

10    g
11    e
12    e
13    k
14    s
dtype: object


# using random

In [11]:
Val = np.random.randint(1500,2000,6)
pd.Series(Val)

0    1789
1    1865
2    1612
3    1914
4    1547
5    1658
dtype: int32

# 2 Find the attributes of Series of [10,30,40,1,3,6,14,18,23] with index starts from 100

In [12]:
series = [10,30,40,1,3,6,14,18,23]
ser = len(series)

In [15]:
ser = pd.Series(series,index = range(100,100+ser))
ser

100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int64

In [16]:
ser

100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int64

In [17]:
ser.info()  # discribing the ser info

<class 'pandas.core.series.Series'>
RangeIndex: 9 entries, 100 to 108
Series name: None
Non-Null Count  Dtype
--------------  -----
9 non-null      int64
dtypes: int64(1)
memory usage: 204.0 bytes


In [18]:
ser.head()  # It is taking the first 5 values from ser

100    10
101    30
102    40
103     1
104     3
dtype: int64

In [19]:
ser.head(2)

100    10
101    30
dtype: int64

In [20]:
ser.tail() # It is taking the last 5 values from ser

104     3
105     6
106    14
107    18
108    23
dtype: int64

In [21]:
ser.tail(3)

106    14
107    18
108    23
dtype: int64

In [22]:
ser.dtype

dtype('int64')

In [23]:
ser.describe()

count     9.000000
mean     16.111111
std      13.033078
min       1.000000
25%       6.000000
50%      14.000000
75%      23.000000
max      40.000000
dtype: float64

In [24]:
ser.memory_usage()

204

In [25]:
ser.size

9

In [26]:
ser.item

<bound method IndexOpsMixin.item of 100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int64>

In [27]:
ser.ndim

1

In [28]:
ser.astype('int32')

100    10
101    30
102    40
103     1
104     3
105     6
106    14
107    18
108    23
dtype: int32

In [29]:
ser.nbytes

72

# 3 create salaries of 30 employee salaries randomly from 30000-90000 then measure and describe the data using pandas series.

In [30]:
salaries = np.random.randint(30000,90000,30)
salaries

array([72566, 80530, 36259, 48491, 86708, 70837, 60323, 72570, 79760,
       69581, 67286, 69434, 58829, 66154, 75351, 30742, 81485, 40326,
       62689, 43121, 60806, 60537, 87116, 80693, 83164, 56319, 59635,
       72695, 65436, 74648])

In [31]:
sal = pd.Series(salaries, index = range(1,31))
sal

1     72566
2     80530
3     36259
4     48491
5     86708
6     70837
7     60323
8     72570
9     79760
10    69581
11    67286
12    69434
13    58829
14    66154
15    75351
16    30742
17    81485
18    40326
19    62689
20    43121
21    60806
22    60537
23    87116
24    80693
25    83164
26    56319
27    59635
28    72695
29    65436
30    74648
dtype: int32

# statistical measures

#measure of central tendency

In [32]:
sal.mean() #Average value

65803.03333333334

In [33]:
sal.median() #middle value for salary

68360.0

In [34]:
sal.mode()  # no repeated values from salary

0     30742
1     36259
2     40326
3     43121
4     48491
5     56319
6     58829
7     59635
8     60323
9     60537
10    60806
11    62689
12    65436
13    66154
14    67286
15    69434
16    69581
17    70837
18    72566
19    72570
20    72695
21    74648
22    75351
23    79760
24    80530
25    80693
26    81485
27    83164
28    86708
29    87116
dtype: int32

In [35]:
sal.var()

216210486.8609195

In [36]:
sal.max()  #The highest value

87116

In [37]:
sal.min()  #The lowest value

30742

In [38]:
sal.std()

14704.09762144279

In [39]:
sal.quantile(0.25)  

59807.0

In [42]:
sal.quantile(0.75)

75175.25

In [43]:
sal.describe()

count       30.000000
mean     65803.033333
std      14704.097621
min      30742.000000
25%      59807.000000
50%      68360.000000
75%      75175.250000
max      87116.000000
dtype: float64

# 4 What are the similaraties and differences between pandas series and nnumpy array.Prove it with code.

In [44]:
#list
age = (range(30,50))

In [45]:
import numpy as np
np.array(age)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [46]:
pd.Series(age)

0     30
1     31
2     32
3     33
4     34
5     35
6     36
7     37
8     38
9     39
10    40
11    41
12    42
13    43
14    44
15    45
16    46
17    47
18    48
19    49
dtype: int64

In [47]:
a= np.array([31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49])
age = pd.Series(a)

In [48]:
age

0     31
1     32
2     33
3     34
4     35
5     36
6     37
7     38
8     39
9     40
10    41
11    42
12    43
13    44
14    45
15    46
16    47
17    48
18    49
dtype: int32

In [49]:
age.ndim  # panda as 1 D/data type either it is rows or columns

1

In [50]:
ages = np.array([1,2,3,4,5,6,7,8,9],ndmin = 3)
ages   #numpy doesnt has index numbers

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [51]:
ages.ndim  # numpy as 3 D

3

# pandas

* pandas as cantain dissmilar data type is Hetrogeneous values




* 1 D array > series (rows or columns)

  2 D array > Data frame(rows and column)
  
  3 D array > panel(images)
  




* Pandas as Data types int,float,bool,Text = object




*  more memorey



# numpy

*Numpy is a numerical  values


*numpy is homogeneous values


*numpy as Data types is int8,16,32,63
              > float 16,32,64
*it is open source library


*numpy works with [n Dimensional array]


*less memorey

# 5 create pandas series with ranges from 100 to 150 then apply indexing and slicing on it.

In [69]:
values = (range(100,150))
val = pd.Series(val)
val


0     100
1     101
2     102
3     103
4     104
5     105
6     106
7     107
8     108
9     109
10    110
11    111
12    112
13    113
14    114
15    115
16    116
17    117
18    118
19    119
20    120
21    121
22    122
23    123
24    124
25    125
26    126
27    127
28    128
29    129
30    130
31    131
32    132
33    133
34    134
35    135
36    136
37    137
38    138
39    139
40    140
41    141
42    142
43    143
44    144
45    145
46    146
47    147
48    148
49    149
dtype: int64

In [70]:
val[46]        # Indexing

146

In [74]:
val[10:35:5]   # slicing

10    110
15    115
20    120
25    125
30    130
dtype: int64